### ISSUE TITLE
Error on installing on Laravel 5.4

### ISSUE THREAD

**Issue by ufeg02** [pusher/pusher-http-laravel#29]
When I try to install puser-http-laravel I get the following error:

Using version ^4.0 for pusher/pusher-http-laravel
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for pusher/pusher-http-laravel ^4.0 -> satisfiable by pusher/pusher-http-laravel[v4.0.0].
    - Conclusion: remove laravel/framework v5.4.36
    - Conclusion: don't install laravel/framework v5.4.36
    - pusher/pusher-http-laravel v4.0.0 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, v5.5.16, v5.5.17, v5.5.2].
    - don't install illuminate/support v5.5.0|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.16|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.17|don't install laravel/framework v5.4.36
    - don't install illuminate/support v5.5.2|don't install laravel/framework v5.4.36
    - Installation request for laravel/framework (locked at v5.4.36, required as 5.4.*) -> satisfiable by laravel/framework[v5.4.36].

This is my composer.json file:

{
    "name": "laravel/laravel",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "type": "project",
    "require": {
        "php": ">=7.1.1",
        "alexpechkarev/google-maps": "1.0.8",
        "cviebrock/eloquent-sluggable": "4.2.5",
        "hipsterjazzbo/landlord": "^2.0",
        "laracasts/flash": "^3.0",
        "laravel/framework": "5.4.*",
        "laravel/passport": "^4.0",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.2.0",
        "musonza/chat": "^2.0",
        "santigarcor/laratrust": "5.0.*",
        "yajra/laravel-datatables-oracle": "^7.0"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.7"
    },
    "autoload": {
        "classmap": [
            "database"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-root-package-install": [
            "php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "php artisan key:generate"
        ],
        "post-install-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postInstall",
            "php artisan optimize"
        ],
        "post-update-cmd": [
            "Illuminate\\Foundation\\ComposerScripts::postUpdate",
            "php artisan optimize"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true,
        "platform": {
            "php": "7.1.1"
        }
    }
}

**Comment by ufeg02** [comment]
Fixed!

**Comment by kn100** [comment]
For future reference, could you let me know how you fixed this?

**Comment by ufeg02** [comment]
I had some unused packages that were not compatible with some depencies of this package.

**Comment by stueynet** [comment]
I am getting the same error @ufeg02. Any chance you could provide even more detail? Which were the problem packages?
