### ISSUE TITLE
Class 'Pusher\Laravel\PusherServiceProvider' not found

### ISSUE THREAD

**Issue by fluvios** [pusher/pusher-http-laravel#36]
hello i want to ask, whats the problem with my code ? i used laravel 5.3.2 and pusher/pusher-http-laravel 2.3.0

in array providers
Pusher\Laravel\PusherServiceProvider::class,

in array aliases
'Pusher' => Pusher\Laravel\Facades\Pusher::class,

[Symfony\Component\Debug\Exception\FatalThrowableError] Class 'Pusher\Laravel\PusherServiceProvider' not found

**Comment by fluvios** [comment]
sorry, i found solutions, change the array providers to Vinkla\Pusher\PusherServiceProvider::class.

hope this it helps

**Comment by WillSewell** [comment]
Yes that is true of older version of this library. An alternative solution is to update the version of this library.
