### ISSUE TITLE
Pusher::trigger always false in laravel 5.6

### ISSUE THREAD

**Issue by asterism612** [pusher/pusher-http-laravel#37]
how to solve?

Pusher::trigger('test-chat', 'test-msg', ['user' => 'tester', 'text' => 'test']);

 42         'main' => [
 43             'auth_key' => env('PUSHER_APP_KEY'),
 44             'secret' => env('PUSHER_APP_SECRET'),
 45             'app_id' => env('PUSHER_APP_ID'),
 46             'options' => [
 47                 'debug' => true,
 48                 'cluster' => env('PUSHER_APP_CLUSTER'),
 49                 'encrypted' => false
 50             ],
 51             'host' => null,
 52             'port' => null,
 53             'timeout

**Comment by kn100** [comment]
Hey - can you contact support@pusher.com with your query? Thanks!
