### ISSUE TITLE
Set up the new GitHub Hook for Packagist

### ISSUE THREAD

**Issue by jameshfisher** [pusher/pusher-http-laravel#40]
Pusher-http-laravel composer github integration is going to break in early 2019. Worth fixing now. Error "This package is using the legacy GitHub service and will stop being auto-updated in early 2019. Please set up the new GitHub Hook for Packagist so that it keeps working in the future."

**Comment by kn100** [comment]
It's probably something only we can fix, since we own the organization. Thanks for your interest though!

**Comment by simPod** [comment]
Just managed it for my own repos by signing out and in using github (it asked for github permissions)

**Comment by WillSewell** [comment]
This has been done.
