### ISSUE TITLE
Pusher beams integration

### ISSUE THREAD

**Issue by namelivia** [pusher/pusher-http-laravel#43]
This package offers a wrapper around pusher-http-laravel, it has a notify function that sends a notification a native notification via the Push Notifications Api, as this is going to be replaced, would it be convenient wrapping push-notifications-php aswell and reusing this method (or adding a new one) but keeping this wrapper package or do you consider that it would be better making a new wrapper just for push-notifications? I can help with both if needed.

**Comment by namelivia** [comment]
Currently because my client is in kind of a hurry I've created [this laravel wrapper](https://github.com/namelivia/push-notifications-laravel) for pusher beams which I intended to keep as similar to the laravel wrapper you have (most of the code is copied indeed, hope its ok) but wraps push-notifications-php.

**Comment by WillSewell** [comment]
Thanks for sharing your Laravel Beams wrapper!

The current plan is to keep SDKs for Channels and Beams separate, so the approach you have taken is the right one!

I'll close this issue, but if you want to discuss your Laravel wrapper for Beams, then feel free to discuss with the team on this [slack group](https://feedback-beta.pusher.com/).
