### ISSUE TITLE
Deprecate this SDK

### ISSUE THREAD

**Issue by WillSewell** [pusher/pusher-http-laravel#55]
[Laravel Broadcasting](https://laravel.com/docs/5.8/broadcasting) now includes built-in support for Pusher Channels via the [pusher-http-php](https://github.com/pusher/pusher-http-php/) SDK. This is now the recommended way of using Channels with Laravel. We should deprecate this repository.

I propose we:

* Set the Github repository as "archived"
* Mention the library is deprecated in the README
* "Abandon" the project on packagist
* Remove it from https://pusher.com/docs/channels/channels_libraries/libraries

**Comment by WillSewell** [comment]
@vinkla do you know whether there is any motivation to use this library over Laravel Broadcasting?

**Comment by vinkla** [comment]
This package was created in early 2015. Not sure if Laravel's Broadcasting features existed back then. The reason I kept this package alive was due to the number of users:

Package | Total Downloads | Monthly Downloads
------- | --------------- | -----------------
`pusher/pusher-http-laravel ` | 147242 | 9077
`vinkla/pusher` | 356229 | 2837

**Comment by GrahamCampbell** [comment]
I still use this package (well, actually, I had to fork it because support for LTS laravel was dropped, and I need the latest manager version).

**Comment by WillSewell** [comment]
Thanks for the information, both.

I think given the fairly substantial usage, I would like to change the plan to:

* Update the readme to mention use of this library is no longer the recommended approach
* Remove it from https://pusher.com/docs/channels/channels_libraries/libraries

We (Pusher) will continue to review any PRs and solve security vulnerabilities in this SDK, but will not be making any major investments into it going forward.

**Comment by GrahamCampbell** [comment]
Does Laravel's broadcasting support encryption?

**Comment by WillSewell** [comment]
I haven't tested it, but it should do. You should be able to set `encryption_master_key` in the `options` config and it should just work™️.

**Comment by GrahamCampbell** [comment]
I wonder what version of Laravel supports encryption. I doubt 5.5 LTS does. ;)

**Comment by GrahamCampbell** [comment]
Maybe the deprecation of this package should be considered again after Laravel 5.9 LTS drops in a couple of months (or sooner, not sure if the release is planned for late July or August).

**Comment by WillSewell** [comment]
It should still work. The encryption depends on libsodium. This has been included in the PHP standard library since 7.2. On earlier versions of PHP, libsodium package from PECL can be used. The version of Laravel shouldn't matter.

**Comment by GrahamCampbell** [comment]
The version will matter if the code needed to enable encryption isn't in there.
